version: '3.8'
services:
  app:
    image: node:16
    command: sh -c "npm install && npm rebuild && node bot.js"
    working_dir: /usr/src/cultureman
    volumes:
      - ./:/usr/src/cultureman
    env_file:
      - ./.env.local