query ($search: String, $page: Int, $perPage: Int) {
  Page(page: $page, perPage: $perPage) {
    media(search: $search, type: ANIME, sort: POPULARITY_DESC) {
      id
      source
      episodes
      title {
        english
        romaji
        native
      }
      coverImage {
        large
      }
      bannerImage
      genres
      averageScore
      status
      description(asHtml: false)
      siteUrl
      nextAiringEpisode {
        airingAt
        episode
      }
      startDate {
        year
        month
        day
      }
      endDate {
        year
        month
        day
      }
    }
  }
}