mutation ($mediaId: Int) {
  SaveMediaListEntry(mediaId: $mediaId, status: PLANNING) {
    id
    media {
      siteUrl
      title {
        userPreferred
      }
      bannerImage
      coverImage {
        large
      }
    }
  }
}
