query ($studio: String, $page: Int) {
  Studio(search: $studio) {
    name
    siteUrl
    favourites
    media(page: $page) {
      pageInfo{
        perPage
        hasNextPage
      }
      nodes {
        title {
          romaji
          native
          english
        }
        siteUrl
      }
    }
  }
}