query ($studio: String) {
  Studio(search: $studio) {
    name
    siteUrl
    favourites
    media {
      nodes {
        title {
          romaji
          native
          english
        }
        siteUrl
      }
    }
  }
}